import SwiftUI
import AVFoundation

@main
struct TikTokTVApp: App {
    init() {

        try? AVAudioSession.sharedInstance()
            .setCategory(.playback, mode: .moviePlayback, policy: .longFormAudio)
    }

    var body: some Scene {
        WindowGroup { ContentView() }
    }
}

struct ContentView: View {
    @StateObject private var service = FeedService()
    @State private var showSettings = !Config.hasCustomServer

    var body: some View {
        ZStack {
            Color.black.ignoresSafeArea()

            if showSettings {
                SettingsView { address in
                    Config.setBackendBaseURL(address)
                    showSettings = false
                    Task { await service.load() }
                }
            } else if !service.items.isEmpty {
                VerticalFeedView(items: service.items,
                                 loadMore: { await service.loadMore() })
                    .ignoresSafeArea()
            } else if let err = service.errorText {
                VStack(spacing: 16) {
                    Text("Couldn't load feed").font(.title2).bold()
                    Text(err).font(.callout).foregroundStyle(.secondary)
                    Text("Server: \(Config.backendBaseURLString)")
                        .font(.footnote).foregroundStyle(.secondary)
                    Button("Change Server") { showSettings = true }
                        .buttonStyle(.bordered)
                        .padding(.top, 8)
                }
                .foregroundStyle(.white)
                .multilineTextAlignment(.center)
                .padding(80)
            } else {
                LoadingView()
            }
        }
        .task {
            if !showSettings { await service.load() }
        }
    }
}

// Uses the real brand mark (LogoMark.imageset — generated by generate_icons.py
// from the same SVG note path as the app icon, NOT a placeholder built out of
// stacked SF Symbols) instead of the old fake "two offset music notes + text"
// approximation. No wordmark — the glyph alone, centered, is the whole screen.
struct LoadingView: View {
    var body: some View {
        VStack(spacing: 36) {
            Image("LogoMark")
                .resizable()
                .scaledToFit()
                .frame(width: 160, height: 160)
            ProgressView().tint(.white).scaleEffect(1.4)
        }
    }
}
